<Project>
  <PropertyGroup>
    <Version Condition="'$(Version)' == ''">0.0.0-local</Version>
    <FileVersion Condition="'$(FileVersion)' == ''">0.0.0.0</FileVersion>
    <InformationalVersion Condition="'$(InformationalVersion)' == ''">0.0.0-local</InformationalVersion>
    <DatabaseSchemaVersion>2</DatabaseSchemaVersion>
  </PropertyGroup>
</Project>
